version: '3'

tasks:
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - go tool templ generate --watch --proxy="http://localhost:8090" --cmd="go run ./cmd/server/main.go" --open-browser=false

  tailwind-clean:
    desc: Clean tailwind output
    cmds:
      - tailwindcss -i ./views/assets/css/input.css -o ./views/assets/css/output.css --clean

  tailwind-watch:
    desc: Run tailwindcss in watch mode
    cmds:
      - tailwindcss -i ./views/assets/css/input.css -o ./views/assets/css/output.css --watch

  dev:
    desc: Start development server with hot reload
    deps:
      - tailwind-clean
    cmds:
      - task --parallel tailwind-watch templ

  build:
    desc: build the server and CLI
    cmds:
      - templ generate
      - go build -o dist/server ./cmd/server
      - go install ./cmd/blkhell

  server:
    desc: Run the server
    deps:
      - build
    cmds:
      - ./dist/server
