version: '3'

tasks:
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - go tool templ generate --watch --proxy="http://localhost:8090" --cmd="go run ./main.go" --open-browser=false

  tailwind-clean:
    desc: Clean tailwind output
    cmds:
      - tailwindcss -i ./views/assets/css/input.css -o ./views/assets/css/output.css --clean

  tailwind-watch:
    desc: Run tailwindcss in watch mode
    cmds:
      - tailwindcss -i ./views/assets/css/input.css -o ./views/assets/css/output.css --watch

  dev:
    desc: Start development server with hot reload
    deps:
      - tailwind-clean
    cmds:
      - task --parallel tailwind-watch templ
