// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bands.sql

package database

import (
	"context"
)

const createBand = `-- name: CreateBand :one
INSERT INTO bands (
    id,
    name,
    country
) VALUES (?, ?, ?)
RETURNING id, name, country, created_at, updated_at
`

type CreateBandParams struct {
	ID      string
	Name    string
	Country string
}

func (q *Queries) CreateBand(ctx context.Context, arg CreateBandParams) (Band, error) {
	row := q.db.QueryRowContext(ctx, createBand, arg.ID, arg.Name, arg.Country)
	var i Band
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBand = `-- name: DeleteBand :exec
;

DELETE FROM bands
WHERE id = ?
`

func (q *Queries) DeleteBand(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBand, id)
	return err
}

const getBandByID = `-- name: GetBandByID :one
;

SELECT id, name, country, created_at, updated_at FROM bands
WHERE id = ?
`

func (q *Queries) GetBandByID(ctx context.Context, id string) (Band, error) {
	row := q.db.QueryRowContext(ctx, getBandByID, id)
	var i Band
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBands = `-- name: GetBands :many
;

SELECT id, name, country, created_at, updated_at FROM bands
ORDER BY name
`

func (q *Queries) GetBands(ctx context.Context) ([]Band, error) {
	rows, err := q.db.QueryContext(ctx, getBands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Band
	for rows.Next() {
		var i Band
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Country,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBand = `-- name: UpdateBand :one
;

UPDATE bands
SET name = ?,
country = ?,
updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, country, created_at, updated_at
`

type UpdateBandParams struct {
	Name    string
	Country string
	ID      string
}

func (q *Queries) UpdateBand(ctx context.Context, arg UpdateBandParams) (Band, error) {
	row := q.db.QueryRowContext(ctx, updateBand, arg.Name, arg.Country, arg.ID)
	var i Band
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Country,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
