// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package database

import (
	"context"
)

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM files WHERE owner_type = 'label') AS label_assets,
    (SELECT COUNT(*) FROM bands) AS bands,
    (SELECT COUNT(*) FROM releases) AS releases,
    (SELECT COUNT(*) FROM projects) AS projects
`

type GetDashboardStatsRow struct {
	LabelAssets int64
	Bands       int64
	Releases    int64
	Projects    int64
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.LabelAssets,
		&i.Bands,
		&i.Releases,
		&i.Projects,
	)
	return i, err
}
