// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package database

import (
	"context"
	"time"
)

const getDashboardBands = `-- name: GetDashboardBands :many
SELECT
    b.id AS band_id,
    b.name AS band_name,
    b.country,
    b.created_at,
    COUNT(DISTINCT r.id) AS release_count,
    COUNT(DISTINCT p.id) AS project_count,
    COUNT(DISTINCT CASE WHEN p.status = 'done' THEN p.id END) AS projects_done
FROM bands b
LEFT JOIN releases r ON b.id = r.band_id
LEFT JOIN projects p ON b.id = p.band_id
GROUP BY b.id, b.name, b.country, b.created_at
ORDER BY b.created_at DESC
`

type GetDashboardBandsRow struct {
	BandID       string
	BandName     string
	Country      string
	CreatedAt    time.Time
	ReleaseCount int64
	ProjectCount int64
	ProjectsDone int64
}

func (q *Queries) GetDashboardBands(ctx context.Context) ([]GetDashboardBandsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDashboardBands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardBandsRow
	for rows.Next() {
		var i GetDashboardBandsRow
		if err := rows.Scan(
			&i.BandID,
			&i.BandName,
			&i.Country,
			&i.CreatedAt,
			&i.ReleaseCount,
			&i.ProjectCount,
			&i.ProjectsDone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    (SELECT COUNT(*) FROM files WHERE owner_type = 'label')
        AS label_assets_count,
    (SELECT COUNT(*) FROM bands) AS bands_count,
    (SELECT COUNT(*) FROM releases) AS releases_count,
    (SELECT COUNT(*) FROM projects) AS projects_count,

    -- these values could null (no records are in these tables),
    -- so non-null values must be used as a fallback
    COALESCE((SELECT id FROM bands ORDER BY created_at DESC LIMIT 1), '')
        AS latest_band_id,
    COALESCE((SELECT name FROM bands ORDER BY created_at DESC LIMIT 1), '')
        AS latest_band_name,

    COALESCE((SELECT id FROM releases ORDER BY created_at DESC LIMIT 1), '')
        AS latest_release_id,
    COALESCE((SELECT name FROM releases ORDER BY created_at DESC LIMIT 1), '')
        AS latest_release_title,

    COALESCE((SELECT id FROM projects ORDER BY created_at DESC LIMIT 1), '')
        AS latest_project_id,
    COALESCE((SELECT name FROM projects ORDER BY created_at DESC LIMIT 1), '')
        AS latest_project_name
`

type GetDashboardStatsRow struct {
	LabelAssetsCount   int64
	BandsCount         int64
	ReleasesCount      int64
	ProjectsCount      int64
	LatestBandID       interface{}
	LatestBandName     interface{}
	LatestReleaseID    interface{}
	LatestReleaseTitle interface{}
	LatestProjectID    interface{}
	LatestProjectName  interface{}
}

func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.LabelAssetsCount,
		&i.BandsCount,
		&i.ReleasesCount,
		&i.ProjectsCount,
		&i.LatestBandID,
		&i.LatestBandName,
		&i.LatestReleaseID,
		&i.LatestReleaseTitle,
		&i.LatestProjectID,
		&i.LatestProjectName,
	)
	return i, err
}
