// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package database

import (
	"context"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    id,
    user_id,
    path,
    filename,
    ext,
    size,
    mimetype,
    owner_type,
    owner_id
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at
`

type CreateFileParams struct {
	ID        string
	UserID    string
	Path      string
	Filename  string
	Ext       string
	Size      int64
	Mimetype  string
	OwnerType string
	OwnerID   string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.ID,
		arg.UserID,
		arg.Path,
		arg.Filename,
		arg.Ext,
		arg.Size,
		arg.Mimetype,
		arg.OwnerType,
		arg.OwnerID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Path,
		&i.Filename,
		&i.Ext,
		&i.Size,
		&i.Mimetype,
		&i.OwnerType,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :one
;

DELETE FROM files
WHERE id = ?
RETURNING id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at
`

func (q *Queries) DeleteFile(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRowContext(ctx, deleteFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Path,
		&i.Filename,
		&i.Ext,
		&i.Size,
		&i.Mimetype,
		&i.OwnerType,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
;

SELECT id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at FROM files
WHERE id = ?
`

func (q *Queries) GetFileByID(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Path,
		&i.Filename,
		&i.Ext,
		&i.Size,
		&i.Mimetype,
		&i.OwnerType,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByPartialName = `-- name: GetFileByPartialName :many
;

SELECT id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at
FROM files
WHERE filename LIKE ?
OR ext like ?
`

type GetFileByPartialNameParams struct {
	Filename string
	Ext      string
}

func (q *Queries) GetFileByPartialName(ctx context.Context, arg GetFileByPartialNameParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFileByPartialName, arg.Filename, arg.Ext)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Path,
			&i.Filename,
			&i.Ext,
			&i.Size,
			&i.Mimetype,
			&i.OwnerType,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFiles = `-- name: GetFiles :many
;

SELECT id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at FROM files
ORDER BY filename
`

func (q *Queries) GetFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Path,
			&i.Filename,
			&i.Ext,
			&i.Size,
			&i.Mimetype,
			&i.OwnerType,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
