// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package database

import (
	"context"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    id,
    user_id,
    path,
    filename,
    ext,
    size,
    mimetype,
    owner_type,
    owner_id,
    audio_duration_seconds
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at, audio_duration_seconds
`

type CreateFileParams struct {
	ID                   string
	UserID               string
	Path                 string
	Filename             string
	Ext                  string
	Size                 int64
	Mimetype             string
	OwnerType            string
	OwnerID              string
	AudioDurationSeconds int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.ID,
		arg.UserID,
		arg.Path,
		arg.Filename,
		arg.Ext,
		arg.Size,
		arg.Mimetype,
		arg.OwnerType,
		arg.OwnerID,
		arg.AudioDurationSeconds,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Path,
		&i.Filename,
		&i.Ext,
		&i.Size,
		&i.Mimetype,
		&i.OwnerType,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AudioDurationSeconds,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :one
;

DELETE FROM files
WHERE id = ?
RETURNING id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at, audio_duration_seconds
`

func (q *Queries) DeleteFile(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRowContext(ctx, deleteFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Path,
		&i.Filename,
		&i.Ext,
		&i.Size,
		&i.Mimetype,
		&i.OwnerType,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AudioDurationSeconds,
	)
	return i, err
}

const getBandImageFilesByID = `-- name: GetBandImageFilesByID :many
;

SELECT id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at, audio_duration_seconds FROM files
WHERE owner_type = 'band'
AND mimetype LIKE 'image/%'
AND owner_id = ?
ORDER BY filename
`

func (q *Queries) GetBandImageFilesByID(ctx context.Context, ownerID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getBandImageFilesByID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Path,
			&i.Filename,
			&i.Ext,
			&i.Size,
			&i.Mimetype,
			&i.OwnerType,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AudioDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileByID = `-- name: GetFileByID :one
;

SELECT id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at, audio_duration_seconds FROM files
WHERE id = ?
`

func (q *Queries) GetFileByID(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Path,
		&i.Filename,
		&i.Ext,
		&i.Size,
		&i.Mimetype,
		&i.OwnerType,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AudioDurationSeconds,
	)
	return i, err
}

const getFileByPartialName = `-- name: GetFileByPartialName :many
;

SELECT id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at, audio_duration_seconds
FROM files
WHERE filename LIKE ?
OR ext like ?
`

type GetFileByPartialNameParams struct {
	Filename string
	Ext      string
}

func (q *Queries) GetFileByPartialName(ctx context.Context, arg GetFileByPartialNameParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFileByPartialName, arg.Filename, arg.Ext)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Path,
			&i.Filename,
			&i.Ext,
			&i.Size,
			&i.Mimetype,
			&i.OwnerType,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AudioDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFiles = `-- name: GetFiles :many
;

SELECT id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at, audio_duration_seconds FROM files
ORDER BY filename
`

func (q *Queries) GetFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Path,
			&i.Filename,
			&i.Ext,
			&i.Size,
			&i.Mimetype,
			&i.OwnerType,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AudioDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLabelImageFiles = `-- name: GetLabelImageFiles :many
;

SELECT id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at, audio_duration_seconds FROM files
WHERE owner_type = 'label'
AND mimetype LIKE 'image/%'
ORDER BY filename
`

func (q *Queries) GetLabelImageFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getLabelImageFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Path,
			&i.Filename,
			&i.Ext,
			&i.Size,
			&i.Mimetype,
			&i.OwnerType,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AudioDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectImageFilesByID = `-- name: GetProjectImageFilesByID :many
;

SELECT id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at, audio_duration_seconds FROM files
WHERE owner_type = 'project'
AND mimetype LIKE 'image/%'
AND owner_id = ?
ORDER BY filename
`

func (q *Queries) GetProjectImageFilesByID(ctx context.Context, ownerID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getProjectImageFilesByID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Path,
			&i.Filename,
			&i.Ext,
			&i.Size,
			&i.Mimetype,
			&i.OwnerType,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AudioDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleaseAudioFilesByID = `-- name: GetReleaseAudioFilesByID :many
;

SELECT id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at, audio_duration_seconds FROM files
WHERE owner_type = 'release'
AND mimetype LIKE 'audio/%'
AND owner_id = ?
ORDER BY filename
`

func (q *Queries) GetReleaseAudioFilesByID(ctx context.Context, ownerID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getReleaseAudioFilesByID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Path,
			&i.Filename,
			&i.Ext,
			&i.Size,
			&i.Mimetype,
			&i.OwnerType,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AudioDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleaseImageFilesByID = `-- name: GetReleaseImageFilesByID :many
;

SELECT id, user_id, path, filename, ext, size, mimetype, owner_type, owner_id, created_at, updated_at, audio_duration_seconds FROM files
WHERE owner_type = 'release'
AND mimetype LIKE 'image/%'
AND owner_id = ?
ORDER BY filename
`

func (q *Queries) GetReleaseImageFilesByID(ctx context.Context, ownerID string) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getReleaseImageFilesByID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Path,
			&i.Filename,
			&i.Ext,
			&i.Size,
			&i.Mimetype,
			&i.OwnerType,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AudioDurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
