// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Image struct {
	ID        string
	UserID    string
	Path      string
	Filename  string
	Ext       string
	Size      int64
	CreatedAt time.Time
}

type Session struct {
	ID        string
	Token     string
	UserID    string
	ExpiresAt time.Time
	CreatedAt sql.NullTime
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	Role         string
	CreatedAt    sql.NullTime
}
