// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Band struct {
	ID        string
	Name      string
	Country   string
	CreatedAt time.Time
	UpdatedAt time.Time
	Removed   int64
}

type File struct {
	ID        string
	UserID    string
	Path      string
	Filename  string
	Ext       string
	Size      int64
	Mimetype  string
	OwnerType string
	OwnerID   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Project struct {
	ID        string
	BandID    string
	ReleaseID string
	Name      string
	Type      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Release struct {
	ID        string
	BandID    string
	Name      string
	Type      string
	Number    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Session struct {
	ID        string
	Token     string
	UserID    string
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           string
	Username     string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
