// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package database

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    id,
    band_id,
    release_id,
    name,
    type
) VALUES (?, ?, ?, ?, ?)
RETURNING id, band_id, release_id, name, type, created_at, updated_at
`

type CreateProjectParams struct {
	ID        string
	BandID    string
	ReleaseID string
	Name      string
	Type      string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.BandID,
		arg.ReleaseID,
		arg.Name,
		arg.Type,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.BandID,
		&i.ReleaseID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
;

DELETE FROM projects
WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
;

SELECT id, band_id, release_id, name, type, created_at, updated_at
FROM projects
WHERE id = ?
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.BandID,
		&i.ReleaseID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjects = `-- name: GetProjects :many
;

SELECT id, band_id, release_id, name, type, created_at, updated_at FROM projects
ORDER BY name
`

func (q *Queries) GetProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.BandID,
			&i.ReleaseID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsByRelease = `-- name: GetProjectsByRelease :many
;

SELECT id, band_id, release_id, name, type, created_at, updated_at
FROM projects
WHERE release_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetProjectsByRelease(ctx context.Context, releaseID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProjectsByRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.BandID,
			&i.ReleaseID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
;

UPDATE projects
SET name = ?,
type = ?,
updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, band_id, release_id, name, type, created_at, updated_at
`

type UpdateProjectParams struct {
	Name string
	Type string
	ID   string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject, arg.Name, arg.Type, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.BandID,
		&i.ReleaseID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
