// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"
	"time"
)

const createImage = `-- name: CreateImage :one
;

INSERT INTO images (id, user_id, path, filename, ext, size)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, user_id, path, filename, ext, size, created_at
`

type CreateImageParams struct {
	ID       string
	UserID   string
	Path     string
	Filename string
	Ext      string
	Size     int64
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, createImage,
		arg.ID,
		arg.UserID,
		arg.Path,
		arg.Filename,
		arg.Ext,
		arg.Size,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Path,
		&i.Filename,
		&i.Ext,
		&i.Size,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
;

INSERT INTO sessions (id, token, user_id, expires_at)
VALUES (?, ?, ?, ?)
RETURNING id, token, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	ID        string
	Token     string
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, password_hash, role)
VALUES (?, ?, ?, ?)
RETURNING id, username, password_hash, role, created_at
`

type CreateUserParams struct {
	ID           string
	Username     string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
;

DELETE FROM sessions
WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteImage = `-- name: DeleteImage :exec
;

DELETE FROM images
WHERE id = ?
`

func (q *Queries) DeleteImage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
;

DELETE FROM sessions
WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteUserByUsername = `-- name: DeleteUserByUsername :exec
;

DELETE FROM users WHERE username = ?
`

func (q *Queries) DeleteUserByUsername(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteUserByUsername, username)
	return err
}

const getImageByID = `-- name: GetImageByID :one
;

SELECT id, user_id, path, filename, ext, size, created_at FROM images
WHERE id = ?
`

func (q *Queries) GetImageByID(ctx context.Context, id string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByID, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Path,
		&i.Filename,
		&i.Ext,
		&i.Size,
		&i.CreatedAt,
	)
	return i, err
}

const getImages = `-- name: GetImages :many
;

SELECT id, user_id, path, filename, ext, size, created_at FROM images
ORDER BY filename
`

func (q *Queries) GetImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, getImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Path,
			&i.Filename,
			&i.Ext,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByToken = `-- name: GetSessionByToken :one
;

SELECT id, token, user_id, expires_at, created_at FROM sessions
WHERE token = ?
AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
;

SELECT id, username, password_hash, role, created_at FROM users
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
;

SELECT id, username, password_hash, role, created_at FROM users
WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
;

UPDATE users
SET username = ?, password_hash = ?, role = ?
WHERE id = ?
RETURNING id, username, password_hash, role, created_at
`

type UpdateUserParams struct {
	Username     string
	PasswordHash string
	Role         string
	ID           string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
