// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: releases.sql

package database

import (
	"context"
)

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases (
    id,
    band_id,
    name,
    type,
    number,
    song_count
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, band_id, name, type, number, created_at, updated_at, song_count
`

type CreateReleaseParams struct {
	ID        string
	BandID    string
	Name      string
	Type      string
	Number    string
	SongCount int64
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, createRelease,
		arg.ID,
		arg.BandID,
		arg.Name,
		arg.Type,
		arg.Number,
		arg.SongCount,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.BandID,
		&i.Name,
		&i.Type,
		&i.Number,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SongCount,
	)
	return i, err
}

const deleteRelease = `-- name: DeleteRelease :exec
;

DELETE FROM releases
WHERE id = ?
`

func (q *Queries) DeleteRelease(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRelease, id)
	return err
}

const getReleaseByID = `-- name: GetReleaseByID :one
;

SELECT id, band_id, name, type, number, created_at, updated_at, song_count FROM releases
WHERE id = ?
`

func (q *Queries) GetReleaseByID(ctx context.Context, id string) (Release, error) {
	row := q.db.QueryRowContext(ctx, getReleaseByID, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.BandID,
		&i.Name,
		&i.Type,
		&i.Number,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SongCount,
	)
	return i, err
}

const getReleases = `-- name: GetReleases :many
;

SELECT id, band_id, name, type, number, created_at, updated_at, song_count FROM releases
ORDER BY name
`

func (q *Queries) GetReleases(ctx context.Context) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, getReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.BandID,
			&i.Name,
			&i.Type,
			&i.Number,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SongCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleasesByBand = `-- name: GetReleasesByBand :many
;

SELECT id, band_id, name, type, number, created_at, updated_at, song_count FROM releases
WHERE band_id = ?
ORDER BY name DESC
`

func (q *Queries) GetReleasesByBand(ctx context.Context, bandID string) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, getReleasesByBand, bandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.BandID,
			&i.Name,
			&i.Type,
			&i.Number,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SongCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReleasesFromPreviousYear = `-- name: GetReleasesFromPreviousYear :many
;

SELECT id, band_id, name, type, number, created_at, updated_at, song_count FROM releases WHERE created_at >= DATE('now', '-1 year')
`

func (q *Queries) GetReleasesFromPreviousYear(ctx context.Context) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, getReleasesFromPreviousYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.BandID,
			&i.Name,
			&i.Type,
			&i.Number,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SongCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelease = `-- name: UpdateRelease :one
UPDATE releases
SET name = ?,
type = ?,
number = ?,
song_count = ?,
updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, band_id, name, type, number, created_at, updated_at, song_count
`

type UpdateReleaseParams struct {
	Name      string
	Type      string
	Number    string
	SongCount int64
	ID        string
}

func (q *Queries) UpdateRelease(ctx context.Context, arg UpdateReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, updateRelease,
		arg.Name,
		arg.Type,
		arg.Number,
		arg.SongCount,
		arg.ID,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.BandID,
		&i.Name,
		&i.Type,
		&i.Number,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SongCount,
	)
	return i, err
}
